[tasks.dev]
run = "bun run ./src/index.ts"

[tasks."build:bun"]
description = "Build the project using Bun"
run = "bun build ./src/index.ts --target=bun --outfile=./bin/adk"

[tasks."build:docker"]
description = "Build the Docker image for the project"
run = "docker build --no-cache -t adk-pi ."

[tasks.build]
description = "Build the project using Bun and Docker"
run = "mise run build:bun && mise run build:docker"

